* All Ears English


** 1007 - 2018.8.29 A Big(little) Announcement that You Don't Want to Miss

This is all ears English 1007, A big/little announcement that you
don't want to miss.  Welcome to the all ears English podcast
downloaded more than 55 million times.  We believe in connection, not
perfection with your American hosts, Lindsay Micman, the English
adventurer and Michelle Cablit, the New York radio girl, coming to you
from Boston and New York city, USA.  And to get your script delivered
by e-mail everyweek, go to www.allearsenglish.com/subscribe.


Today we answer a listener's letter about congratulating people and I
will share a big exciting piece of news with you guys for the first
time.

Hello, Lindsay, how's it going?

It's excellent.  Michelle, how are you doing?

I'm good, I'm good.  I have a question.  Do you have any friend who
are currently pregnant?

Oh, my gosh.  Let's see, let's see.  No, not a that I know of.

Okay, all right.  Well, Interesting.  Today we have a question having
kind of to deal with that question.

Before we got to that.  I want to thank those who have reviewes us on
itune.  Right, Lindsay?

Yes, but we love our reviewers.  I'll send out these reviews.  They
are so good for us to see and helping you guys.  I'll call out some
of our reviewers.

...Names from countries/area...

All these people, these listeners gave us 5 star reviews.  We are so
appreciate it you guys.  Thank you so much for this.  We love this.
We are so...  If you haven't reviewed us yet, go into your podcast app
or into our app into ios app and leave us a review.  We are so
appreciated and we are going to announce your name on the show.


Today, Lindsay, we have a listener's question about congratulating
people.  And guys, I want you to stay.  Make sure you keep listening,
because I have a big announcement coming up.

Big exciting announcement you guys don't want to miss up.

No, No, NO. So yeah.  But before that, we are going to got into our
listener's question.  So Lindsay, would you read it for us.

Yes, so here we go. Okay

Hi, many, It's Lily, I'm from Korea.  I can't tell you how much I have
enjoyed your podcast.  I listen to it almost everyday.  And I learned
a lot from it.  I want to give you guys a huge shout out.  Ooh, sounds
very natural, Lily. That's really good, yeah ,really.  Are you shout
out for your great work on the podcast?  Let me get straight to my
question.  The other day, my friend who have gone through multiple
miscarriages told me that she was pregnant with her rainbow baby which
was amazing.  So I said I'm so happy for you to congratulate her
pregnancy.  I couldn't think of any other expression.  So my question
is: can you gie me better expressions or phrases to congratulate
people on milestones like wedding, a baby shower, graduation, other
than I'm happy for you.  Thanks in advance.

Oh, good question Lily.

Okay, awesome.  It's a great question.  Right, because we want more
new ones in our expressions even things like congratulating people.
We want, u know, build that skill.  So I want to start out for
something.  First, so what is a rainbow babyy.  Do you know Lindsay?

I've no idea.  Do you know?

A rainbow baby is the baby that someone has after suffering a loss of
another baby, because she had miscarriages.  I think it is a multiple
miscarriages.  It's terrible.  So this is her rainbow.  So it's I
think it comes from like a rainbow after a storm.

Oh, that makes sense.  That makes sense.  Okay good.  That makes a lot
of sense.  Perfect.  It's very important in this case, specially
important that we say the right thing, that we really, really, really
make sure that our friends know that how happy we are.

Yeah, I mean Lindsay what do you think of the phrase I'm so happy for
you.  I mean it's fine, it just, it's neutral, it's one of your
options.  Yeah, I'm so happy for you.  I don't have any problem with
it.  But I think we can help our listener Lily here and other
listeners to expand their options.

Yeah, yeah, definitely.  I mean.  I don't see any issue with that
phrase.  I think it's a great one to use.  So you know we are going to
give your a few new ones that you could say so.  What's the first one
Lindsay?

All right.  So what fantastic news right?  Or, what amazing news.  Or
what great news.  So we can throw in adjectives here guys.  It sounds
super natural when we do that.

Right.  The task is amazing, awesome, something like that, right?
Yeah, exactly, that's very natural.

So he next one.  I like this one as the second part congratulations or
anything like that.  And then "This makes my day!"

We can do a whole episode on this concept.  Oh, this makes my day.
You make my day.

Well I like it because it's like ooh saying how happy you are also
personally like that. It like really affected you.  Like there are
good news going to affected you in such a deep way.

Yeah, interesting, that you use it here.  I totally understand how we
can use it and we can say it.  And often it's used in a more like if
someone does something for you directly, like ooh, you are having a
bad day and someone got you an icecream.  Ooh, you made my day.  You
got me an icecream.  But I like how we are taking this and we are
using it because to celebrate someone else's joy.

I think it just makes the person feel like even more or less deeper
connection to you, for sure, because you are letting their joy affect
you so much in such a big way.

I think we should do another episode on this phrase itself.  But I
like this.  This is like a really strong connection phrase.  Because
you are right.  It would make them feel really close to you like wow
this news about me being pregnant could make your day so much better.
That's really cool.

And what's one more thing you could say Lindsay?

So you could say "I wish you all the happiness in the world."

That's a little bit more formal.  But I think it's a really nice thing
to say.

You could also write this on a card.

Ooh yeah.

I would feel a little bit...  This phrase is not exactly my personal
style.  Because it's a little longwinded and a little formal.  But
I'll write it for sure in a card, for sure, you know in a baby shower
something like that.  

That's a good idea.  That's a good point.  I like that too.  I know
you mentioned graduation, wedding, and other things.  So, but today we
are going to focus on pregnancy.

And there is a little/big announcement that I would like to make.  So
guys I am pregnant.

I want to, I thought this is the perfect question to anounce my
pregnancy to our listeners.  I want to let you guys know because you
are really important to my life as well.  This podcast is huge part of
my life you know.  I had chance to meet so many listeners and you guys
feel like friends.  We really care about you and I really want to let
you know.  So I was so excited to tell everybody.  Very exciting news.

That's wonderful Michelle.  I'm so excited for you.  Our listeners who
came to New York day they know already.  But the rest of our community
here did not know.  And this is gonna be so fun.  May be we could have
the baby on the show at some point.

Very exciting.  Feeling good.  It's just been... I think [people have
been] keep talking about how hard it is.  I think it's because like
pregnant women have a higher body temprature.  I bet it has really
been tough in this summer.  So it's even hotter.  like I feel a few
degrees warmer for me than everybody.  I think it's already hot out
there.  But other than that things are good.

I mean I would ask you some follow up questions like I absolutely knew
this before today's episode.

That would be something if I told you and you don't know.

That would be crazy.  But if I didn't know, what could I ask, what
could I say right after I say congratulations to follow up and dig in
deeper.

Yeah, we have a few phrases that you could say like that somebody tell
you that she's pregnant.

"When are you due?" like the due date, the date that when the baby is
coming.

"Do you know what you are having?"  Do you know of the girl or boy.

It's a little bit. 

Do you think it's ok to ask this?

Gees.  I don't know my [if pregnancy at a kid update all that much]
but I would like to ask you if that's okay.

How do you feel when people ask you that?

I personally think it's okay.  Everybody is different.  I think this
is prettty neutral question.  Not everybody knows.  Not everybody
finds out.  I'll tell you what I'm having in a second when we are
doing the role play.  I had to find out right away like I couldn't
wait to find out.  It's not like I had to find out because I really
want one or the other.  But I have friends who just say oh they want a
surprise when they have the baby.  I am curious like about that kind
of culture around the world.  like do most people find out?  where you
from?  Is it more common to find out?  like you know this is a whole
conversation we could have.

Yeah guys come back to our blog and let us know in your country is it
common to find out the gender of the baby ahead of time.  And how did
that work?  Is that okay to ask that question?  Come back to
allearsenglish.com/episode.  That's where you find our blog and type
in 1007.  Okay, love that.

Right, right, right, definitely.

I mean I don't see anything wrong with it.  But the person may not
know, yeah, if they are early on.  They may decide they don't want to
know.  That's how you would ask do you know what you are having.

I don't think it would offend anyone.

But there is one question that I know is annoying.  I don't ask it,
but I always want to ask it.  Do you know what it is?

No, what?

The question is about names.  Everyone wants like a way in.  But
that's the problem.  That why most people usually don't say names at
least in modern culture that people in my world, that they are having
babies, they tend to not share possible names on their list with
family and friends because they know that everyone just gonna way in.
And everyone knows someone with that name.

Oh, I work with a guy with that name.

He was a jerk.

Yeah.

What has been your experience?  I'm not gonna ask you any possible
names of course.  I'm so curious like I...

The answer is I don't know the name yet.  I have like a list of
[voik], a hundred know.  I have a bunch of names.  Nothing like quite
jumping out to me.  I'm a terrible decision-maker.  So I'm a little
bit...yeah...that's gonna be a tough one.

Typically what I say is like oh I'm not asking for what it is.  But
I'm just curious.  Do you know the name?  like you have decided.

But I think it is a good way to put the pressure off someone.  But
it's good to let our listeners to know that at least here in American
culture in like, I guess in our world like urban, like east coastt
world US, we tend not to ask specially.  We don't put the pressure on
someone like what the name are you thinking about.  That kind of
[forpaul] these days.

Everybody is different.  I have had friends and family members who
like said the name even you don't even have to ask.  They just told.
They were just excited to say it.  Everybody has different opinion.
Generally speaking, the people that I know at least they don't reveal
the name until the baby is born.

I don't know if I knew my brother's choice.

Even like within family sometimes in my experience, it is not revealed.

And I think it is specially within family, because as you said, like
you know, I mean if you say the name like you tell your mama oh I'm
naming my baby whatever and she makes a face.  Then you are gonna
start a second guess for everything.  So you are gonna choose a name
you like.

...a lot to say about that one.

And then there's one more question that I thought it was pretty
important.  Do you know what it is?

Yeah, you would just say "How have you been feeling?  How's been
going?"  That's fine.  That's great, just checking in.  "How's
everything been?"

Because different people have different kinds of pregnancies.  Some
are easier, some are harder, it depends

Let's give it a try  in our role play.

... role play conversation ...


